READABLE = {
    'mean_consumption': 'Mean consumption',
    'median_consumption': 'Median consumption',
    'total_consumption': 'Total consumption',
    'std_consumption': 'Consumption std. deviation',
    'min_consumption': 'Minimum consumption',
    'max_consumption': 'Maximum consumption',
    'range_consumption': 'Consumption range',
    'q25_consumption': '25th-percentile consumption',
    'q75_consumption': '75th-percentile consumption',
    'q90_consumption': '90th-percentile consumption',
    'q95_consumption': '95th-percentile consumption',
    'skewness_consumption': 'Consumption skewness',
    'kurtosis_consumption': 'Consumption kurtosis',
    'total_readings': 'Total number of readings',
    'non_zero_readings': 'Number of non-zero readings',
    'zero_consumption_ratio': 'Zero-consumption ratio',
    'iqr_consumption': 'Consumption interquartile range',
    'morning_avg_consumption': 'Morning average consumption',
    'afternoon_avg_consumption': 'Afternoon average consumption',
    'evening_avg_consumption_x': 'Evening average consumption',
    'evening_avg_consumption_y': 'Evening average consumption',
    'night_avg_consumption_x': 'Night average consumption',
    'night_avg_consumption_y': 'Night average consumption',
    'peak_consumption_hour': 'Peak consumption hour',
    'weekend_avg_consumption': 'Weekend average consumption',
    'weekday_avg_consumption': 'Weekday average consumption',
    'weekend_weekday_ratio': 'Weekend-to-weekday consumption ratio',
    'day_0_avg_consumption': 'Monday average consumption',
    'day_1_avg_consumption': 'Tuesday average consumption',
    'day_2_avg_consumption': 'Wednesday average consumption',
    'day_3_avg_consumption': 'Thursday average consumption',
    'day_4_avg_consumption': 'Friday average consumption',
    'day_5_avg_consumption': 'Saturday average consumption',
    'day_6_avg_consumption': 'Sunday average consumption',
    'monthly_consumption_variability': 'Monthly consumption variability',
    'self_disconnect_events': 'Self-disconnection event count',
    'self_disconnect_ratio': 'Self-disconnection ratio',
    'max_consecutive_zeros': 'Max. consecutive zero readings',
    'avg_consecutive_zeros': 'Avg. consecutive zero readings',
    'very_low_consumption_count': 'Very-low-consumption count',
    'very_low_consumption_ratio': 'Very-low-consumption ratio',
    'evening_zero_ratio': 'Evening zero-consumption ratio',
    'consumption_volatility': 'Consumption volatility',
    'daily_consumption_std': 'Daily consumption std. deviation',
    'daily_consumption_cv': 'Daily consumption coefficient of variation',
    'below_avg_consumption_ratio': 'Below-average consumption ratio',
    'winter_avg_consumption': 'Winter average consumption',
    'winter_min_consumption': 'Winter minimum consumption',
    'winter_zero_ratio': 'Winter zero-consumption ratio',
    'sharp_drop_count': 'Sharp consumption drop count',
    'sharp_drop_ratio': 'Sharp consumption drop ratio',
    'weekend_evening_avg': 'Weekend evening average consumption',
    'consumption_regularity': 'Consumption regularity',
    'load_factor': 'Load factor',
    'base_load': 'Base load',
    'base_load_avg': 'Average base load',
    'peak_to_base_ratio': 'Peak-to-base-load ratio',
    'avg_ramp_rate': 'Average ramp rate',
    'max_ramp_rate': 'Maximum ramp rate',
    'ramp_rate_std': 'Ramp rate std. deviation',
    'peak_demand_hours': 'Peak demand hours',
    'peak_demand_ratio': 'Peak demand ratio',
    'off_peak_avg': 'Off-peak average consumption',
    'off_peak_ratio': 'Off-peak consumption ratio',
    'on_peak_avg': 'On-peak average consumption',
    'load_diversity': 'Load diversity',
    'cv_consumption': 'Coefficient of variation (consumption)',
    'iqr_normalized': 'Normalised interquartile range',
    'range_normalized': 'Normalised consumption range',
    'mad_consumption': 'Mean absolute deviation (consumption)',
    'median_ad_consumption': 'Median absolute deviation (consumption)',
    'variance_to_mean': 'Variance-to-mean ratio',
    'consistency_score': 'Consistency score',
    'consumption_entropy': 'Consumption entropy',
    'distinct_consumption_levels': 'Distinct consumption levels',
    'mode_frequency': 'Modal-value frequency',
    'winter_avg': 'Winter average consumption',
    'winter_std': 'Winter consumption std. deviation',
    'winter_min': 'Winter minimum consumption',
    'winter_max': 'Winter maximum consumption',
    'winter_zero_count': 'Winter zero-consumption count',
    'winter_evening_avg': 'Winter evening average consumption',
    'winter_night_avg': 'Winter night average consumption',
    'winter_to_annual_ratio': 'Winter-to-annual consumption ratio',
    'winter_volatility': 'Winter consumption volatility',
    'winter_self_disconnect': 'Winter self-disconnection count',
    'quintile_1': 'Lowest consumption quintile (indicator)',
    'quintile_2': '2nd consumption quintile (indicator)',
    'quintile_3': '3rd consumption quintile (indicator)',
    'quintile_4': '4th consumption quintile (indicator)',
    'quintile_5': 'Highest consumption quintile (indicator)',
}

def readable(name):
    return READABLE.get(name, name)
